In [2]:
import numpy as np

In [3]:
arr = np.array(((1,2,3),(4,5,6),(7,8,9)))

In [4]:
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [5]:
print(arr.ravel())

[1 2 3 4 5 6 7 8 9]


In [6]:
print(arr.reshape((-1,)))

[1 2 3 4 5 6 7 8 9]
